apiVersion: v1
kind: Service
metadata:
  name: authservice-backend
  namespace: production
  labels:
    app: authservice-backend
spec:
  selector:
    app: authservice-backend
  ports:
  - name: http
    port: 3010
    targetPort: 3010
  type: ClusterIP
